spring:
  datasource:
    username: postgres
    password: 6268
    url: jdbc:postgresql://localhost:3308/ShoppingCartDb
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
 

    
